### ISSUE TITLE
Request some functionalities upstream

### ISSUE THREAD

**Issue by Arusekk** [romkatv/libgit2#2]
While I know that this fork is mainly a do-not-merge and many changes are `gitstatusd`-specific, it introduces quite a lot nice features, like querying `pushRemote`, improving concurrency/fixing data races, as well as many other fixes.

I believe upstream can benefit from some of the optimizations or functionalities that were created here. Just as an idea, I think it would be good to submit a PR upstream with all the changes that are not targeted only at `gitstatusd`. It may also reduce the maintenance burden, which grows the bigger, the bigger the change set.

BTW, I love the speed of powerlevel10k, great job :)

**Comment by romkatv** [comment]
I've tried submitting changes upstream to libgit2 but it didn't have much of an effect. See https://github.com/libgit2/libgit2/issues/5038, https://github.com/libgit2/libgit2/issues/4230#issuecomment-471710359 (starting from the linked comment and below) and follow links from these if you are curious.

My fork is open source, so anyone is free to submit PRs or do with it as they please (within the constraints of GPL).
