### ISSUE TITLE
Differences between this fork and the original?

### ISSUE THREAD

**Issue by jason5122** [romkatv/libgit2#4]
Hi, I stumbled across your fork from your gitstatus repo and was wondering if it is mature enough to be used in an app in terms of bugs/features. I find the major performance boosts listed in your Why Fast section very appealing and saw your opened issues in the main libgit2 repo about merging, so I assume this is very close to being useable if it isn't already.

Also, let me know if the performance boosts have already been merged into the main repo. If so, I will use that one instead.

**Comment by romkatv** [comment]
This fork is not supposed to be used anywhere except https://github.com/romkatv/gitstatus. It's not a drop-in replacement for the stock libgit2 (it used to be but not anymore) and there are no guarantees nor support for it.

> I assume this is very close to being useable if it isn't already.

It's very usable for https://github.com/romkatv/gitstatus.

> let me know if the performance boosts have already been merged into the main repo.

None of the performance optimizations from this fork have been merged by the upstream.
